name = "SVP Member Portal Login Check"
type = "login_check"
url = "https://svpcrmportal.m-cloudapps.com/Account/Login"
username = "ne_michaelrice"
password = "January2024!!!"
success = 302
[payload]
username = "UserName"
password = "Password"
csrf_element = "__RequestVerificationToken"
